### ISSUE TITLE
KeyError: 'runtime' on aws-cli example

### ISSUE THREAD

**Issue by JohnCoates** [grycap/scar#268]
This error popped up. Running SCAR from a docker container
from scar.log:
```
2018-07-30 12:05:39,559 - root - ERROR - 'runtime'
Traceback (most recent call last):
  File "/app/scar/src/exceptions.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/app/scar/src/providers/aws/lambdafunction.py", line 67, in create_function
    creation_args = self.get_creations_args()
  File "/app/scar/src/providers/aws/lambdafunction.py", line 52, in get_creations_args
    'Runtime' : self.properties['runtime'],
KeyError: 'runtime'
```

python 3.6.5 packages listed with `pip3 list`
```
asn1crypto (0.24.0)
boto3 (1.7.65)
botocore (1.10.65)
certifi (2018.4.16)
chardet (3.0.4)
configparser (3.5.0)
cryptography (2.1.4)
docutils (0.14)
idna (2.7)
jmespath (0.9.3)
keyring (10.6.0)
keyrings.alt (3.0)
pip (9.0.1)
pycrypto (2.6.1)
pygobject (3.26.1)
python-dateutil (2.7.3)
pyxdg (0.25)
PyYAML (3.13)
requests (2.19.1)
s3transfer (0.1.13)
SecretStorage (2.3.1)
setuptools (39.0.1)
six (1.11.0)
tabulate (0.8.2)
urllib3 (1.23)
wheel (0.30.0)
```

I found this error while trying to get scar running inside a docker container. Details for the container are below.

Dockerfile
```
FROM ubuntu:18.04
RUN apt-get -qq update && apt-get install -y \
  git python3 python3-pip curl zip \
  && rm -r /var/lib/apt/lists/*
WORKDIR /app
EXPOSE 8080
RUN useradd --create-home --shell /bin/bash virtual
USER virtual
ENTRYPOINT bash
```

docker-compose.yml
```
version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: scar
    ports:
      - 8080:8080
    volumes:
      - ./scar:/app/scar
      - ./scarConfig:/home/virtual/.scar
      - ./aws:/home/virtual/.aws
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
```
