### ISSUE TITLE
'Unmanaged Exception in Invoke' when defining parameters

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#282]
Defining a function with the following YAML:
```
functions:
    scar-cowsay:
      image: grycap/cowsay
      init_script: test-cowsay.sh
      api_gateway:
        name: cow-api
```
and invoking the function supplying parameters:

```
scar invoke -f api-cow.yaml -p '{"A":"14"}'
```
Results in the following error:
```
There was an unmanaged exception in invoke
```
